// Code generated by tygo. DO NOT EDIT.

//////////
// source: shared-types.go

/**
 * Go to TUI
 */
export const MessageTypeConnected = "connected";
export const MessageTypeDisconnected = "disconnected";
export const MessageTypeReconnecting = "reconnecting";
export const MessageTypeKeysExchanged = "keys_exchanged";
export const MessageTypeMessage = "message";
/**
 * Go <-> Go (ws) and Go to TUI
 */
export const MessageTypeUserEnteredChat = "user_entered_chat";
export const MessageTypeUserLeftChat = "user_left_chat";
export const MessageTypeCurrentUsers = "current_users";
export const MessageTypeSuccess = "success";
export const MessageTypeError = "error";
/**
 * Go <-> Go (ws)
 */
export const MessageTypeExchangeKeys = "exchange_keys";
export const MessageTypeEncryptedMessage = "encrypted_message";
export const MessageTypeJoinRoom = "join_room";
export const MessageTypeLeaveRoom = "leave_room";
export const MessageTypeCreateRoom = "create_room";
export const MessageTypeDeleteRoom = "delete_room";
/**
 * TUI to Go
 */
export const MessageTypeConnect = "connect";
export const MessageTypeSend = "send";
export type MessageType = typeof MessageTypeConnected | typeof MessageTypeDisconnected | typeof MessageTypeReconnecting | typeof MessageTypeKeysExchanged | typeof MessageTypeMessage | typeof MessageTypeUserEnteredChat | typeof MessageTypeUserLeftChat | typeof MessageTypeCurrentUsers | typeof MessageTypeSuccess | typeof MessageTypeError | typeof MessageTypeExchangeKeys | typeof MessageTypeEncryptedMessage | typeof MessageTypeJoinRoom | typeof MessageTypeLeaveRoom | typeof MessageTypeCreateRoom | typeof MessageTypeDeleteRoom | typeof MessageTypeConnect | typeof MessageTypeSend;
